"""Microsoft Foundry Toolbox Agent Skills integration for Deep Agents."""

from __future__ import annotations

import asyncio
import logging
import threading
import time
from datetime import timedelta
from pathlib import PurePosixPath

from azure.core.credentials import TokenCredential
from azure.identity import DefaultAzureCredential

try:
    from deepagents.backends.protocol import (
        BackendProtocol,
        DeleteResult,
        EditResult,
        FileData,
        FileDownloadResponse,
        FileInfo,
        FileUploadResponse,
        GlobResult,
        GrepResult,
        LsResult,
        ReadResult,
        WriteResult,
    )
    from deepagents.backends.utils import (
        file_data_to_string,
        grep_matches_from_files,
        slice_read_response,
    )
except ImportError as ex:
    raise ImportError(
        "FoundryToolboxSkillsBackend requires the 'deepagents' optional "
        "dependency. Install it with:\n  pip install langchain-azure-ai[deepagents]"
    ) from ex

from langchain_azure_ai._api.base import experimental
from langchain_azure_ai.tools._toolbox import AzureAIProjectToolbox

logger = logging.getLogger(__name__)


@experimental()
class FoundryToolboxSkillsBackend(BackendProtocol):
    """Read-only, refreshable Toolbox skill source rooted at ``/``.

    The source fetches Agent Skills through ``AzureAIProjectToolbox`` and keeps
    an immutable in-memory snapshot. Refreshes are serialized, and a failed
    refresh preserves the last good snapshot.

    Args:
        project_endpoint: Microsoft Foundry project endpoint.
        toolbox_name: Name of the Toolbox that contains Agent Skills.
        credential: Azure credential used to authenticate Toolbox MCP requests.
        api_version: Toolbox API version. Defaults to ``"v1"``.
        disable_caching: Re-query the Toolbox before every metadata scan.
        cache_refresh_interval: Maximum age of a cached snapshot. ``None`` keeps
            the first successful snapshot indefinitely; zero refreshes every scan.
    """

    def __init__(
        self,
        project_endpoint: str,
        toolbox_name: str,
        credential: TokenCredential | str | None = None,
        *,
        api_version: str = "v1",
        disable_caching: bool = False,
        cache_refresh_interval: timedelta | None = None,
    ) -> None:
        """Initialize a refreshable Toolbox Agent Skills source."""
        self._toolbox = AzureAIProjectToolbox(
            project_endpoint=project_endpoint,
            toolbox_name=toolbox_name,
            api_version=api_version,
            credential=credential or DefaultAzureCredential(),
        )
        self._disable_caching = disable_caching
        self._cache_refresh_interval = cache_refresh_interval
        self._refreshed_at = 0.0
        self._has_snapshot = False
        self._refresh_lock = threading.Lock()
        self._snapshot_lock = threading.RLock()
        self._snapshot: dict[str, FileData] = {}

    @property
    def endpoint(self) -> str:
        """Return the consumer endpoint generated by AzureAIProjectToolbox."""
        return self._toolbox.toolbox_endpoint

    def _cache_is_fresh(self) -> bool:
        if not self._has_snapshot or self._disable_caching:
            return False
        if self._cache_refresh_interval is None:
            return True
        max_age = max(self._cache_refresh_interval.total_seconds(), 0)
        return time.monotonic() - self._refreshed_at < max_age

    def refresh(self, *, force: bool = True) -> bool:
        """Refresh the snapshot, preserving the last good copy on failure."""
        with self._refresh_lock:
            if not force and self._cache_is_fresh():
                return False
            try:
                files = self._toolbox.get_skills(base_path="/")
                if not files:
                    raise RuntimeError(
                        "The configured Foundry Toolbox exposed no Agent Skills."
                    )
            except Exception:
                if not self._has_snapshot:
                    raise
                logger.warning(
                    "Failed to refresh Agent Skills from %s; keeping the last "
                    "good snapshot.",
                    self.endpoint,
                    exc_info=True,
                )
                return False

            with self._snapshot_lock:
                self._snapshot = {
                    path: FileData(**file_data) for path, file_data in files.items()
                }
                self._refreshed_at = time.monotonic()
                self._has_snapshot = True
            return True

    async def arefresh(self, *, force: bool = True) -> bool:
        """Refresh the snapshot without blocking the event loop."""
        return await asyncio.to_thread(self.refresh, force=force)

    def _refresh_if_stale(self) -> None:
        if not self._cache_is_fresh():
            self.refresh(force=False)

    def _refresh_if_empty(self) -> None:
        if not self._has_snapshot:
            self.refresh(force=False)

    def ls(self, path: str) -> LsResult:
        """List Toolbox skill files and directories."""
        self._refresh_if_stale()
        return self._list_snapshot(path)

    def _list_snapshot(self, path: str) -> LsResult:
        with self._snapshot_lock:
            snapshot = dict(self._snapshot)

        normalized = path.rstrip("/") or "/"
        prefix = "/" if normalized == "/" else f"{normalized}/"
        entries: list[FileInfo] = []
        directories: set[str] = set()
        for file_path, file_data in snapshot.items():
            if not file_path.startswith(prefix):
                continue
            relative = file_path[len(prefix) :]
            if "/" in relative:
                directories.add(f"{prefix}{relative.split('/', 1)[0]}/")
            elif relative:
                entries.append(
                    FileInfo(
                        path=file_path,
                        is_dir=False,
                        size=len(file_data_to_string(file_data)),
                        modified_at=file_data.get("modified_at", ""),
                    )
                )
        entries.extend(
            FileInfo(path=path, is_dir=True, size=0, modified_at="")
            for path in sorted(directories)
        )
        entries.sort(key=lambda entry: entry["path"])
        return LsResult(entries=entries)

    async def als(self, path: str) -> LsResult:
        """List Toolbox skill files without blocking during refresh."""
        if not self._cache_is_fresh():
            await self.arefresh(force=False)
        return self._list_snapshot(path)

    def read(self, file_path: str, offset: int = 0, limit: int = 2000) -> ReadResult:
        """Read a Toolbox skill file."""
        self._refresh_if_empty()
        with self._snapshot_lock:
            file_data = self._snapshot.get(file_path)
            if file_data is None:
                return ReadResult(error=f"File '{file_path}' not found")
            return slice_read_response(file_data, offset, limit)

    def download_files(self, paths: list[str]) -> list[FileDownloadResponse]:
        """Download Toolbox skill files."""
        self._refresh_if_empty()
        with self._snapshot_lock:
            snapshot = dict(self._snapshot)
        return [
            FileDownloadResponse(
                path=path,
                content=(
                    file_data_to_string(snapshot[path]).encode("utf-8")
                    if path in snapshot
                    else None
                ),
                error=None if path in snapshot else "file_not_found",
            )
            for path in paths
        ]

    def grep(
        self,
        pattern: str,
        path: str | None = None,
        glob: str | None = None,
        *,
        max_count: int | None = None,
    ) -> GrepResult:
        """Search Toolbox skill files for literal text."""
        self._refresh_if_empty()
        with self._snapshot_lock:
            return grep_matches_from_files(
                self._snapshot,
                pattern,
                path or "/",
                glob,
                max_count=max_count,
            )

    def glob(self, pattern: str, path: str | None = None) -> GlobResult:
        """Find Toolbox skill files matching a glob pattern."""
        self._refresh_if_empty()
        with self._snapshot_lock:
            snapshot = dict(self._snapshot)
        root = (path or "/").rstrip("/") or "/"
        prefix = "/" if root == "/" else f"{root}/"
        normalized_pattern = pattern.lstrip("/")
        matches = [
            FileInfo(
                path=file_path,
                is_dir=False,
                size=len(file_data_to_string(file_data)),
                modified_at=file_data.get("modified_at", ""),
            )
            for file_path, file_data in snapshot.items()
            if file_path.startswith(prefix)
            and PurePosixPath(file_path[len(prefix) :]).match(normalized_pattern)
        ]
        matches.sort(key=lambda entry: entry["path"])
        return GlobResult(matches=matches)

    @staticmethod
    def _read_only_error(operation: str) -> str:
        return f"Error: Foundry Toolbox Agent Skills are read-only ({operation})."

    def write(self, file_path: str, content: str) -> WriteResult:
        """Reject writes to Toolbox skill files."""
        return WriteResult(error=self._read_only_error("write"))

    def edit(
        self,
        file_path: str,
        old_string: str,
        new_string: str,
        replace_all: bool = False,
    ) -> EditResult:
        """Reject edits to Toolbox skill files."""
        return EditResult(error=self._read_only_error("edit"))

    def delete(self, file_path: str) -> DeleteResult:
        """Reject deletes of Toolbox skill files."""
        return DeleteResult(error=self._read_only_error("delete"))

    def upload_files(self, files: list[tuple[str, bytes]]) -> list[FileUploadResponse]:
        """Reject uploads to the Toolbox skill source."""
        return [
            FileUploadResponse(path=path, error=self._read_only_error("upload"))
            for path, _ in files
        ]


__all__ = ["FoundryToolboxSkillsBackend"]
